import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Palette, Type, MessageSquare, Layout, ChevronDown, Copy, Download, Check } from "lucide-react";
import { brandGuidelines, type BrandGuideline } from "@/data/wateraid-brand-guidelines";

const WATERAID_BLUE = "#0057B8";

export const BrandGuidelinesSection = () => {
  const [expandedId, setExpandedId] = useState<string | null>(brandGuidelines[0]?.outcomeId ?? null);
  const [copied, setCopied] = useState(false);

  const generateExportText = (g: BrandGuideline) => {
    const lines = [
      `═══════════════════════════════════════`,
      `BRAND GUIDELINE: ${g.outcomeStatement.toUpperCase()}`,
      `═══════════════════════════════════════`,
      ``,
      `CORE BRAND COLOR`,
      `  WaterAid Blue: ${WATERAID_BLUE}`,
      ``,
      `SUPPORTING PALETTE`,
      ...g.visualDirection.supportingPalette.map(c => `  ${c.name} (${c.hex}): ${c.usage}`),
      ``,
      `TYPOGRAPHY`,
      `  Heading: ${g.visualDirection.typography.heading}`,
      `  Body: ${g.visualDirection.typography.body}`,
      `  Accent: ${g.visualDirection.typography.accent}`,
      ``,
      `IMAGE STYLE`,
      `  ${g.visualDirection.imageStyle}`,
      ``,
      `ICON STYLE`,
      `  ${g.visualDirection.iconStyle}`,
      ``,
      `TONE OF VOICE`,
      `  Personality: ${g.toneOfVoice.personality.join(", ")}`,
      `  Do Say:`,
      ...g.toneOfVoice.doSay.map(s => `    ✓ "${s}"`),
      `  Don't Say:`,
      ...g.toneOfVoice.dontSay.map(s => `    ✗ "${s}"`),
      `  Sample Headline: "${g.toneOfVoice.sampleHeadline}"`,
      ``,
      `MESSAGING FRAMEWORK`,
      `  Tagline: "${g.messagingFramework.tagline}"`,
      `  Elevator Pitch: ${g.messagingFramework.elevatorPitch}`,
      `  Proof Points:`,
      ...g.messagingFramework.proofPoints.map(p => `    • ${p}`),
      ``,
      `CHANNEL APPLICATION`,
      `  Social: ${g.channelApplication.social}`,
      `  Web: ${g.channelApplication.web}`,
      `  Print: ${g.channelApplication.print}`,
    ];
    return lines.join("\n");
  };

  const exportAll = () => {
    const full = brandGuidelines.map(generateExportText).join("\n\n\n");
    const header = `WATERAID BRAND GUIDELINES\nAligned to Desired Outcomes\nGenerated by InsightEngine\n${"═".repeat(40)}\n\nCore Brand Color: WaterAid Blue (${WATERAID_BLUE})\nThis colour must appear as a consistent primary element across all guidelines.\n\n`;
    const blob = new Blob([header + full], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "wateraid-brand-guidelines.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyAll = () => {
    const full = brandGuidelines.map(generateExportText).join("\n\n\n");
    navigator.clipboard.writeText(full);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4 mb-6">
        <div>
          <h2 className="text-xl font-bold mb-1">Brand Guidelines</h2>
          <p className="text-sm text-muted-foreground">
            Outcome-aligned brand recommendations — anchored in <span className="font-semibold" style={{ color: WATERAID_BLUE }}>WaterAid Blue</span>
          </p>
        </div>
        <div className="flex gap-2">
          <button onClick={copyAll} className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs rounded-lg border border-border hover:bg-secondary transition-colors">
            {copied ? <Check className="w-3.5 h-3.5 text-primary" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? "Copied" : "Copy All"}
          </button>
          <button onClick={exportAll} className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors">
            <Download className="w-3.5 h-3.5" />
            Export .txt
          </button>
        </div>
      </div>

      {/* Consistent brand anchor */}
      <div className="rounded-xl border border-border p-5 flex items-center gap-4" style={{ background: `linear-gradient(135deg, ${WATERAID_BLUE}10, ${WATERAID_BLUE}05)` }}>
        <div className="w-14 h-14 rounded-xl flex-shrink-0 shadow-md" style={{ backgroundColor: WATERAID_BLUE }} />
        <div>
          <h3 className="text-sm font-bold">WaterAid Blue — The Constant</h3>
          <p className="text-xs text-muted-foreground mt-0.5">
            <span className="font-mono" style={{ color: WATERAID_BLUE }}>{WATERAID_BLUE}</span> · HSL 211 100% 36% — Present as the primary brand anchor across every guideline variant. All supporting palettes orbit this colour.
          </p>
        </div>
      </div>

      {/* Guidelines per outcome */}
      <div className="space-y-3">
        {brandGuidelines.map((g, i) => {
          const isOpen = expandedId === g.outcomeId;
          return (
            <motion.div
              key={g.outcomeId}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.04 }}
              className="rounded-xl bg-card border border-border shadow-card overflow-hidden"
            >
              <button
                onClick={() => setExpandedId(isOpen ? null : g.outcomeId)}
                className="w-full px-5 py-4 text-left hover:bg-secondary/30 transition-colors flex items-center gap-3"
              >
                <div className="w-2 h-8 rounded-full flex-shrink-0" style={{ backgroundColor: WATERAID_BLUE }} />
                <div className="flex-1 min-w-0">
                  <p className="font-semibold text-sm truncate">{g.outcomeStatement}</p>
                  <p className="text-xs text-muted-foreground mt-0.5">Tagline: "{g.messagingFramework.tagline}"</p>
                </div>
                <ChevronDown className={`w-4 h-4 text-muted-foreground transition-transform flex-shrink-0 ${isOpen ? "rotate-180" : ""}`} />
              </button>

              <AnimatePresence>
                {isOpen && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    className="overflow-hidden"
                  >
                    <div className="px-5 pb-6 border-t border-border pt-5 space-y-6">
                      {/* Visual Direction */}
                      <section>
                        <h4 className="text-xs font-semibold uppercase text-muted-foreground flex items-center gap-1.5 mb-3">
                          <Palette className="w-3.5 h-3.5" /> Visual Direction
                        </h4>
                        <div className="flex gap-2 flex-wrap mb-3">
                          <div className="flex items-center gap-2 px-3 py-2 rounded-lg border border-border bg-secondary/30">
                            <div className="w-5 h-5 rounded" style={{ backgroundColor: WATERAID_BLUE }} />
                            <span className="text-xs font-medium">WaterAid Blue</span>
                            <span className="text-[10px] font-mono text-muted-foreground">{WATERAID_BLUE}</span>
                          </div>
                          {g.visualDirection.supportingPalette.map(c => (
                            <div key={c.hex} className="flex items-center gap-2 px-3 py-2 rounded-lg border border-border bg-secondary/30">
                              <div className="w-5 h-5 rounded border border-border" style={{ backgroundColor: c.hex }} />
                              <span className="text-xs font-medium">{c.name}</span>
                              <span className="text-[10px] font-mono text-muted-foreground">{c.hex}</span>
                            </div>
                          ))}
                        </div>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
                          <div className="p-3 rounded-lg bg-secondary/30 border border-border">
                            <span className="text-muted-foreground font-medium">Image Style</span>
                            <p className="mt-1 text-foreground/80">{g.visualDirection.imageStyle}</p>
                          </div>
                          <div className="p-3 rounded-lg bg-secondary/30 border border-border">
                            <span className="text-muted-foreground font-medium">Icon Style</span>
                            <p className="mt-1 text-foreground/80">{g.visualDirection.iconStyle}</p>
                          </div>
                        </div>
                      </section>

                      {/* Typography */}
                      <section>
                        <h4 className="text-xs font-semibold uppercase text-muted-foreground flex items-center gap-1.5 mb-3">
                          <Type className="w-3.5 h-3.5" /> Typography
                        </h4>
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                          {Object.entries(g.visualDirection.typography).map(([role, desc]) => (
                            <div key={role} className="p-3 rounded-lg border border-border bg-secondary/30 text-xs">
                              <span className="text-muted-foreground uppercase font-medium">{role}</span>
                              <p className="mt-1 text-foreground/80">{desc}</p>
                            </div>
                          ))}
                        </div>
                      </section>

                      {/* Tone of Voice */}
                      <section>
                        <h4 className="text-xs font-semibold uppercase text-muted-foreground flex items-center gap-1.5 mb-3">
                          <MessageSquare className="w-3.5 h-3.5" /> Tone of Voice
                        </h4>
                        <div className="flex gap-2 flex-wrap mb-3">
                          {g.toneOfVoice.personality.map(p => (
                            <span key={p} className="px-2.5 py-1 text-[11px] font-medium rounded-full text-primary-foreground" style={{ backgroundColor: WATERAID_BLUE }}>
                              {p}
                            </span>
                          ))}
                        </div>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-3">
                          <div className="p-3 rounded-lg border border-border bg-secondary/30 text-xs">
                            <span className="text-primary font-medium">✓ Do Say</span>
                            <ul className="mt-1.5 space-y-1">
                              {g.toneOfVoice.doSay.map(s => <li key={s} className="text-foreground/80">"{s}"</li>)}
                            </ul>
                          </div>
                          <div className="p-3 rounded-lg border border-border bg-secondary/30 text-xs">
                            <span className="text-accent font-medium">✗ Don't Say</span>
                            <ul className="mt-1.5 space-y-1">
                              {g.toneOfVoice.dontSay.map(s => <li key={s} className="text-foreground/80">"{s}"</li>)}
                            </ul>
                          </div>
                        </div>
                        <div className="p-4 rounded-lg border-l-4 bg-secondary/20" style={{ borderColor: WATERAID_BLUE }}>
                          <span className="text-[10px] font-mono text-muted-foreground uppercase">Sample Headline</span>
                          <p className="text-sm font-bold mt-1">"{g.toneOfVoice.sampleHeadline}"</p>
                        </div>
                      </section>

                      {/* Messaging Framework */}
                      <section>
                        <h4 className="text-xs font-semibold uppercase text-muted-foreground flex items-center gap-1.5 mb-3">
                          <Layout className="w-3.5 h-3.5" /> Messaging & Channels
                        </h4>
                        <div className="p-4 rounded-lg border border-border bg-secondary/20 mb-3">
                          <div className="flex items-center gap-2 mb-2">
                            <span className="text-[10px] font-mono text-muted-foreground uppercase">Tagline</span>
                            <span className="text-sm font-bold" style={{ color: WATERAID_BLUE }}>"{g.messagingFramework.tagline}"</span>
                          </div>
                          <p className="text-xs text-foreground/80">{g.messagingFramework.elevatorPitch}</p>
                          <div className="flex flex-wrap gap-1.5 mt-2">
                            {g.messagingFramework.proofPoints.map(p => (
                              <span key={p} className="text-[10px] px-2 py-0.5 rounded bg-primary/10 text-primary">{p}</span>
                            ))}
                          </div>
                        </div>
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                          {Object.entries(g.channelApplication).map(([ch, desc]) => (
                            <div key={ch} className="p-3 rounded-lg border border-border bg-secondary/30 text-xs">
                              <span className="text-muted-foreground font-medium uppercase">{ch}</span>
                              <p className="mt-1 text-foreground/80">{desc}</p>
                            </div>
                          ))}
                        </div>
                      </section>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
};
