import { useState } from "react";
import { Download, Copy, Check, Globe, MapPin, Calendar, Users, Megaphone, Eye, Target, MessageCircle } from "lucide-react";
import { mockCharityProfile } from "@/data/wateraid-profile";
import { mockPains, mockRepositioning } from "@/data/wateraid-mock";

export const CharityProfileSection = () => {
  const profile = mockCharityProfile;
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [selectedMessages, setSelectedMessages] = useState<Set<string>>(
    new Set(profile.keyMessages.map((m) => m.id))
  );

  const toggleMessage = (id: string) => {
    setSelectedMessages((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const generateCampaignScript = () => {
    const selected = profile.keyMessages.filter((m) => selectedMessages.has(m.id));
    const topPains = mockPains.slice(0, 3);
    const topRepo = mockRepositioning.slice(0, 2);

    const lines: string[] = [
      "═══════════════════════════════════════════════════",
      `  CAMPAIGN BRIEF — ${profile.name.toUpperCase()}`,
      "═══════════════════════════════════════════════════",
      "",
      "BRAND OVERVIEW",
      "──────────────",
      `Name:         ${profile.name}`,
      `Tagline:      ${profile.tagline}`,
      `Founded:      ${profile.founded}`,
      `HQ:           ${profile.headquarters}`,
      `Reach:        ${profile.reach}`,
      `Countries:    ${profile.countries}`,
      `Website:      ${profile.website}`,
      "",
      "MISSION",
      profile.mission,
      "",
      "VISION",
      profile.vision,
      "",
      "",
      "═══════════════════════════════════════════════════",
      "  KEY MESSAGES",
      "═══════════════════════════════════════════════════",
      "",
    ];

    selected.forEach((msg, i) => {
      lines.push(`${i + 1}. [${msg.pillar}]`);
      lines.push(`   Headline:       ${msg.headline}`);
      lines.push(`   Supporting Copy: ${msg.supportingCopy}`);
      lines.push(`   Emotional Hook:  ${msg.emotionalHook}`);
      lines.push(`   Proof Point:     ${msg.proofPoint}`);
      lines.push("");
    });

    lines.push("");
    lines.push("═══════════════════════════════════════════════════");
    lines.push("  AUDIENCE INSIGHTS");
    lines.push("═══════════════════════════════════════════════════");
    lines.push("");

    profile.audienceInsights.forEach((a) => {
      lines.push(`▸ ${a.segment}`);
      lines.push(`  Motivation: ${a.motivation}`);
      lines.push(`  Barrier:    ${a.barrier}`);
      lines.push("");
    });

    lines.push("");
    lines.push("═══════════════════════════════════════════════════");
    lines.push("  TONE GUIDELINES");
    lines.push("═══════════════════════════════════════════════════");
    lines.push("");

    profile.toneGuidelines.forEach((t) => {
      lines.push(`▸ ${t.attribute}`);
      lines.push(`  ✓ Do:   ${t.doThis}`);
      lines.push(`  ✗ Don't: ${t.notThis}`);
      lines.push("");
    });

    lines.push("");
    lines.push("═══════════════════════════════════════════════════");
    lines.push("  TOP PAINS (from audience research)");
    lines.push("═══════════════════════════════════════════════════");
    lines.push("");

    topPains.forEach((p, i) => {
      lines.push(`${i + 1}. ${p.title} — Severity: ${p.severity}/5 (${p.mentionRate}% mention rate)`);
      lines.push(`   Theme: ${p.theme}`);
      if (p.quotes[0]) lines.push(`   Quote: "${p.quotes[0].text}" — ${p.quotes[0].source}`);
      lines.push("");
    });

    lines.push("");
    lines.push("═══════════════════════════════════════════════════");
    lines.push("  REPOSITIONING DIRECTION");
    lines.push("═══════════════════════════════════════════════════");
    lines.push("");

    topRepo.forEach((r, i) => {
      lines.push(`${i + 1}. ${r.currentPerception}  →  ${r.desiredPerception}`);
      lines.push(`   Gap:         ${r.gap}`);
      lines.push(`   Opportunity: ${r.opportunity}`);
      lines.push("");
    });

    lines.push("");
    lines.push("───────────────────────────────────────────────────");
    lines.push(`Generated by InsightEngine · ${new Date().toLocaleDateString()}`);
    lines.push("───────────────────────────────────────────────────");

    return lines.join("\n");
  };

  const handleExport = () => {
    const script = generateCampaignScript();
    const blob = new Blob([script], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${profile.name.toLowerCase()}-campaign-brief.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyScript = () => {
    const script = generateCampaignScript();
    copyToClipboard(script, "full-script");
  };

  return (
    <div className="space-y-8">
      {/* Brand header */}
      <div className="p-6 rounded-xl bg-card border border-border shadow-card">
        <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <h2 className="text-2xl font-bold">{profile.name}</h2>
              <span className="px-2 py-0.5 rounded-full bg-primary/10 border border-primary/20 text-xs font-mono text-primary">
                Est. {profile.founded}
              </span>
            </div>
            <p className="text-muted-foreground text-sm mb-4">{profile.tagline}</p>
            <p className="text-sm leading-relaxed max-w-2xl">{profile.mission}</p>
          </div>
          <div className="flex gap-2 shrink-0">
            <button
              onClick={handleCopyScript}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-secondary text-secondary-foreground text-sm font-medium hover:bg-secondary/80 transition-colors"
            >
              {copiedId === "full-script" ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              {copiedId === "full-script" ? "Copied" : "Copy Brief"}
            </button>
            <button
              onClick={handleExport}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 transition-colors"
            >
              <Download className="w-4 h-4" />
              Export .txt
            </button>
          </div>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-6 pt-6 border-t border-border">
          {[
            { icon: MapPin, label: "HQ", value: profile.headquarters },
            { icon: Globe, label: "Countries", value: profile.countries.toString() },
            { icon: Users, label: "People Reached", value: profile.peopleReached },
            { icon: Calendar, label: "Active Since", value: profile.founded.toString() },
          ].map((item) => (
            <div key={item.label} className="flex items-center gap-2.5">
              <item.icon className="w-4 h-4 text-muted-foreground" />
              <div>
                <p className="text-xs text-muted-foreground font-mono uppercase tracking-wider">{item.label}</p>
                <p className="text-sm font-semibold">{item.value}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Key Messages */}
      <div>
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Megaphone className="w-4 h-4 text-primary" />
            <h3 className="text-sm font-semibold uppercase tracking-wider">Key Messages</h3>
          </div>
          <span className="text-xs text-muted-foreground font-mono">
            {selectedMessages.size}/{profile.keyMessages.length} selected for export
          </span>
        </div>

        <div className="space-y-3">
          {profile.keyMessages.map((msg) => {
            const isSelected = selectedMessages.has(msg.id);
            return (
              <div
                key={msg.id}
                className={`p-5 rounded-xl border transition-all cursor-pointer ${
                  isSelected
                    ? "bg-card border-primary/30 shadow-card"
                    : "bg-card/50 border-border/50 opacity-60"
                }`}
                onClick={() => toggleMessage(msg.id)}
              >
                <div className="flex items-start gap-3">
                  <div
                    className={`mt-0.5 w-5 h-5 rounded border-2 flex items-center justify-center shrink-0 transition-colors ${
                      isSelected ? "border-primary bg-primary" : "border-muted-foreground/30"
                    }`}
                  >
                    {isSelected && <Check className="w-3 h-3 text-primary-foreground" />}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1.5">
                      <span className="px-2 py-0.5 rounded-full bg-secondary text-secondary-foreground text-[10px] font-mono uppercase tracking-wider">
                        {msg.pillar}
                      </span>
                    </div>
                    <h4 className="font-semibold text-base mb-2">{msg.headline}</h4>
                    <p className="text-sm text-muted-foreground leading-relaxed mb-3">{msg.supportingCopy}</p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      <div className="flex items-start gap-2">
                        <MessageCircle className="w-3.5 h-3.5 text-accent mt-0.5 shrink-0" />
                        <div>
                          <p className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider">Emotional Hook</p>
                          <p className="text-xs italic">{msg.emotionalHook}</p>
                        </div>
                      </div>
                      <div className="flex items-start gap-2">
                        <Target className="w-3.5 h-3.5 text-info mt-0.5 shrink-0" />
                        <div>
                          <p className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider">Proof Point</p>
                          <p className="text-xs">{msg.proofPoint}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      copyToClipboard(`${msg.headline}\n\n${msg.supportingCopy}\n\nHook: ${msg.emotionalHook}\nProof: ${msg.proofPoint}`, msg.id);
                    }}
                    className="p-1.5 rounded-md hover:bg-secondary transition-colors text-muted-foreground hover:text-foreground shrink-0"
                  >
                    {copiedId === msg.id ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Audience Insights */}
      <div>
        <div className="flex items-center gap-2 mb-4">
          <Eye className="w-4 h-4 text-primary" />
          <h3 className="text-sm font-semibold uppercase tracking-wider">Target Audiences</h3>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {profile.audienceInsights.map((a) => (
            <div key={a.segment} className="p-5 rounded-xl bg-card border border-border shadow-card">
              <h4 className="font-semibold text-sm mb-3">{a.segment}</h4>
              <div className="space-y-3">
                <div>
                  <p className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1">Motivation</p>
                  <p className="text-xs leading-relaxed">{a.motivation}</p>
                </div>
                <div>
                  <p className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1">Barrier</p>
                  <p className="text-xs leading-relaxed text-destructive/80">{a.barrier}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Tone Guidelines */}
      <div>
        <div className="flex items-center gap-2 mb-4">
          <Megaphone className="w-4 h-4 text-primary" />
          <h3 className="text-sm font-semibold uppercase tracking-wider">Tone Guidelines</h3>
        </div>
        <div className="rounded-xl bg-card border border-border shadow-card overflow-hidden">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border">
                <th className="text-left p-4 text-xs font-mono text-muted-foreground uppercase tracking-wider">Attribute</th>
                <th className="text-left p-4 text-xs font-mono text-muted-foreground uppercase tracking-wider">✓ Do This</th>
                <th className="text-left p-4 text-xs font-mono text-muted-foreground uppercase tracking-wider">✗ Not This</th>
              </tr>
            </thead>
            <tbody>
              {profile.toneGuidelines.map((t) => (
                <tr key={t.attribute} className="border-b border-border/50 last:border-0">
                  <td className="p-4 font-medium">{t.attribute}</td>
                  <td className="p-4 text-primary">{t.doThis}</td>
                  <td className="p-4 text-muted-foreground">{t.notThis}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
